services:
  proxy-server:
    image: cheftory-proxy-server:latest
    ports:
      - "8080"
      - "8081"
    depends_on:
      - mysql
    env_file:
      - .env

    #.env 파일을 읽어서 환경변수로 지정
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      AI_RECIPE_SUMMARY_HOST: ${AI_RECIPE_SUMMARY_HOST}
      AI_RECIPE_SUMMARY_PORT: ${AI_RECIPE_SUMMARY_PORT}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      OPENSEARCH_HOST: ${OPENSEARCH_HOST}
      OPENSEARCH_PORT: ${OPENSEARCH_PORT}
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
      COUPANG_PARTNERS_ACCESS_KEY: ${COUPANG_PARTNERS_ACCESS_KEY}
      COUPANG_PARTNERS_SECRET_KEY: ${COUPANG_PARTNERS_SECRET_KEY}
      TZ: Asia/Seoul
    networks:
      - cheftory_network
    restart: always

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: Asia/Seoul
    ports:
      - "3306"
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--init-connect=SET NAMES utf8mb4",
      "--skip-character-set-client-handshake"
    ]
    networks:
      - cheftory_network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379"
    volumes:
      - ./data/redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      - cheftory_network
    restart: always

networks:
  cheftory_network:
    name: cheftory_network
    driver: bridge